name: roboaware
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - _tflow_select=2.3.0
  - absl-py=0.13.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - async-timeout=4.0.1
  - asynctest=0.13.0
  - attrs=21.2.0
  - autopep8=1.5.5
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.10.14
  - cachetools=4.2.2
  - cairo=1.16.0
  - catkin_pkg=0.4.23
  - certifi=2020.6.20
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - colorlog=4.4.0
  - cryptography=3.4.8
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - distro=1.5.0
  - docutils=0.18.1
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freeglut=3.0.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fsspec=2021.10.1
  - future=0.18.2
  - gast=0.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.42.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - intel-openmp=2019.4
  - jasper=2.0.14
  - joblib=1.1.0
  - jpeg=9d
  - jxrlib=1.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.78.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=9.3.0
  - libmklml=2019.0.5
  - libnghttp2=1.46.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-base=3.5.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - multidict=5.1.0
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.6.3
  - ninja=1.10.2
  - numexpr=2.7.3
  - numpy-base=1.19.2
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.4
  - partd=1.2.0
  - pcre=8.45
  - pip=21.2.2
  - pixman=0.40.0
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2021.3
  - pywavelets=1.1.1
  - quaternion=2020.9.5.14.42.2
  - readline=8.1
  - requests-oauthlib=1.3.0
  - rospkg=1.2.10
  - rsa=4.7.2
  - scikit-image=0.17.2
  - scikit-learn=1.0.1
  - scipy=1.6.1
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - stable-baselines3=1.1.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - torchvision=0.8.2
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - werkzeug=2.0.2
  - wheel=0.37.0
  - wrapt=1.13.3
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxcursor=1.2.0
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxinerama=1.1.4
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.10
  - xorg-randrproto=1.5.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.6.3
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appnope==0.1.0
    - backcall==0.2.0
    - cffi==1.14.2
    - cloudpickle==1.3.0
    - configparser==5.0.1
    - cycler==0.10.0
    - docker-pycreds==0.4.0
    - fasteners==0.15
    - flake8==3.8.3
    - gitdb==4.0.5
    - gitpython==3.1.11
    - glfw==2.3.0
    - gym==0.17.2
    - importlib-metadata==2.0.0
    - ipdb==0.13.3
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - kiwisolver==1.2.0
    - matplotlib==3.3.1
    - mccabe==0.6.1
    - monotonic==1.5
    - mujoco-py<2.2,>=2.1
    - numpy==1.19.1
    - opencv-contrib-python==4.5.1.48
    - parso==0.7.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - promise==2.3
    - prompt-toolkit==3.0.7
    - protobuf==3.13.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - pupil-apriltags==1.0.4
    - pyflakes==2.2.0
    - pyglet==1.5.0
    - pygments==2.6.1
    - pyquaternion==0.9.9
    - pyyaml==5.3.1
    - requests==2.24.0
    - sentry-sdk==0.19.2
    - shortuuid==1.0.1
    - smmap==3.0.4
    - subprocess32==3.5.4
    - torch==1.6.0
    - tqdm==4.48.2
    - traitlets==4.3.3
    - urllib3
    - wandb==0.10.10
    - watchdog==0.10.3
    - wcwidth==0.2.5
    - zipp==3.4.0
